brakajmap/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
	url(r'^crime/',include('crime.urls')),
        url(r'^accounts', include('allauth.urls')),
        url(r'^admin/', include(admin.site.urls)),
)

crime/urls.py
from django.conf.urls import patterns, url
from crime import views

urlpatterns = patterns('crime.views',
                       url(r'^acceuil/$', 'acceuil', name='acceuil'),
                       url(r'^new_crime/$', 'add_crime', name='add_crime'),
                       url(r'^thanks/$', 'thanks', name='thanks'),
                       url(r'^statistique/$', 'statistique', name='statistique'),
                       url(r'^supprimer/$', 'delete', name='supprimer'),
                       url(r'^modifier/$', 'modify', name='modifier'),
                       url(r'^statistique/filter/$', 'filtercrime', name='filter'),
                       url(r'stat/', 'stat', name='stat'),
                       url(r'cdata/', 'calendar_data'),
                       url(r'test/', 'test'),
                       url(r'mod/', 'mod_crime')
)

crime/models.py
from django.db import models
from geoposition.fields import GeopositionField


gouv_choice = (
    ('Ariana', 'Ariana'),
    ('Beja', 'Beja'),
    ('Ben Arous', 'Ben Arous'),
    ('Bizerte', 'Bizerte'),
    ('Gabes', 'Gabes'),
    ('Gafsa', 'Gafsa'),
    ('Jendouba', 'Jendouba'),
    ('Kairouan', 'Kairouan'),
    ('Kasserine', 'Kasserine'),
    ('Kebili', 'Kebili'),
    ('Kef', 'Kef'),
    ('Mahdia', 'Mahdia'),
    ('Manouba', 'Manouba'),
    ('Medenine', 'Medenine'),
    ('Monastir', 'Monastir'),
    ('Nabeul', 'Nabeul'),
    ('Sfax', 'Sfax'),
    ('Sidi Bouzid', 'Sidi Bouzid'),
    ('Siliana', 'Siliana'),
    ('Sousse', 'Sousse'),
    ('Tataouine', 'Tataouine'),
    ('Tozeur', 'Tozeur'),
    ('Tunis', 'Tunis'),
    ('Zaghouan', 'Zaghouan'),
)
crime_choice = (
    ('braquage', 'braquage'),
    ('harcelement sexuelle', 'harcelement sexuelle'),
    ('viole', 'viole'),
    ('vol', 'vol'),
    ('agression', 'agression'),
    ('assassinat', 'assassinat'),
    ('kidnap', 'kidnap'),
)
sexchoice = (
    ('Homme', 'Homme'),
    ('Femme', 'Femme'),
)


class crime(models.Model):
    gouvernorat = models.CharField(max_length=30, choices=gouv_choice, default='Tunis', help_text="Gouvernorat:")
    description = models.TextField(help_text="informations:")
    sexe = models.CharField(max_length=15, choices=sexchoice, help_text="sexe")
    time = models.DateTimeField(auto_now_add=False, auto_now=False, verbose_name="Date de crime",
                                help_text="Date et Heure du crime: ")
    position = GeopositionField()
    crimetype = models.CharField(max_length=30, choices=crime_choice, help_text=" crime :")

    def __unicode__(self):
        return 'Tunisie'

crime/forms.py
from django import forms
from crime.models import crime

sexchoice = (
    ('H', 'Homme'),
    ('F', 'Femme'),
)


class crimeForm(forms.ModelForm):
    sexe = forms.ChoiceField(widget=forms.RadioSelect, choices=sexchoice, help_text='sexe:')

    class Meta:
        model = crime

crime/views.py
from __future__ import division
from django.shortcuts import HttpResponse, render
from django.template import RequestContext
from django.db.models.query import Q
from crime.forms import crimeForm
from crime.models import crime
from geoposition import Geoposition
import json
from django.core.serializers.json import DjangoJSONEncoder
from calendar import timegm


def acceuil(request):
    context_dict = {'hello': "Introduction"}
    return render(request, 'crime/acceuil.html', context_dict)


def thanks(request):
    context_dict = {'thx': "merci pour votre participation pour une meilleur tunisie"}
    return render(request, 'crime/thanks.html', context_dict)


def add_crime(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = crimeForm(request.POST)
        var = request.POST['crimetype']

        if form.is_valid():
            form.save(commit=True)
            return thanks(request)
        else:
            print form.errors
    else:

        form = crimeForm()

    return render(request, 'crime/add_crime.html', locals())


def statistique(request):
    return render(request, 'crime/statistique.html', locals())


def delete(request):
    if 'id' not in request.GET:
        return HttpResponse("fail")
    the_id = int(request.GET['id'])
    try:
        obj = crime.objects.get(id=the_id)
        obj.delete()
        return HttpResponse("success ")
    except crime.DoesNotExist:
        return HttpResponse("fail")


def modify(request):
    if request.method == 'GET':
        if 'lat' and 'lng' not in request.GET:
            return HttpResponse("fail no position in get")
        lat = request.GET['lat']
        lng = request.GET['lng']
        try:
            p = Geoposition(lat, lng)
            obj = crime.objects.get(position=p)
            obj_id = obj.id
            gouv = obj.gouvernorat
            desc = obj.description
            sx = obj.sexe
            temp = str(obj.time)[:-6]
            cat = obj.crimetype
            lat = str(obj.position.latitude)
            lon = str(obj.position.longitude)
            dictionnaire = {'id': obj_id,
                            'gouv': gouv,
                            'temp': temp,
                            'desc': desc,
                            'lat': lat,
                            'lon': lon,
                            'sx': sx,
                            'cat': cat}

            return HttpResponse(json.dumps(dictionnaire),
                                content_type='application/json')
        except crime.DoesNotExist:
            return HttpResponse("fail no crime in get")
    elif request.method == 'POST':
        if 'id' not in request.POST:
            return HttpResponse("fail no id")
        the_id = request.POST['id']
        try:
            obj = crime.objects.get(id=the_id)
        except crime.DoesNotExist:
            return HttpResponse("fail no crime")
        if "gouvernorat" in request.POST:
            obj.gouvernorat = request.POST["gouvernorat"]
        if "description" in request.POST:
            obj.description = request.POST["description"]
        if "sexe" in request.POST:
            obj.sexe = request.POST["sexe"]
        if "crimetype" in request.POST:
            obj.crimetype = request.POST["crimetype"]
        if "position" in request.POST:
            position = request.POST["position"]
        if "time" in request.POST:
            obj.time = request.POST["time"]
        obj.save()
        return HttpResponse("succes post")
    else:
        return HttpResponse("fail all")


def filtercrime(request):
    if request.method == "GET":
        sex, gouv, cat = None, None, None
        if "sex" in request.GET:
            sex = request.GET["sexe"]
        if "gouvernorat" in request.GET:
            gouv = request.GET["gouvernorat"]
        if "crimetype" in request.GET:
            cat = request.GET["crimetype"]
        q = Q()
        if sex:
            q = q & Q(sexe=sex)
        if gouv:
            q = q & Q(gouvernorat=gouv)
        if cat:
            q = q & Q(crimetype=cat)
        crimes = crime.objects.filter(q)

        crimes = list(crimes.values_list("gouvernorat", "position", "crimetype", "time"))
        return HttpResponse(json.dumps(crimes, cls=DjangoJSONEncoder), content_type="application/json")
    else:
        return HttpResponse()


def stat(request):
    if request.method == 'GET':
        nbr = crime.objects.count()
        if 'type' in request.GET:
            type_dict = {'braquage': 0,
                         'harcelement sexuelle': 0,
                         'viole': 0,
                         'vol': 0,
                         'agression': 0,
                         'assassinat': 0,
                         'kidnap': 0}
            for i in type_dict:
                type_dict[i] = (crime.objects.filter(Q(crimetype=i)).count() / nbr) * 100
            res = [list(l) for l in type_dict.items()]
            return HttpResponse(json.dumps(res), content_type="application/json")
        elif 'sexe' in request.GET:
            sex_dict = {"Femme": 0, "Homme": 0}
            for s in sex_dict:
                sex_dict[s] = (crime.objects.filter(Q(sexe=s)).count() / nbr) * 100
            res = [list(l) for l in sex_dict.items()]
            return HttpResponse(json.dumps(res), content_type="application/json")
        else:
            return HttpResponse()
    else:
        return HttpResponse()


def calendar_data(request):
    crimes = crime.objects.all().values_list("time", flat=True)
    crimes_stamp = [timegm(i.timetuple()) for i in crimes]
    res = dict(zip([str(i) for i in crimes_stamp], [1 for i in range(len(crimes_stamp))]))
    return HttpResponse(json.dumps(res), content_type="application/json")


def test(request):
    return render(request, 'crime/calendar.html', locals())


def mod_crime(request):
    form = crimeForm()
    return render(request, 'crime/mod_crime.html', locals())

templates/crime/acceuil.html
<!DOCTYPE html>
<html>
{% extends 'crime/base.html' %}
{%  load static %}
<head>
        <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
{% block body_block_left %}
<div class="hero-unit" >
   
</br>
	<h3>{{ hello }} à CriMap :  </h3>
	<p> La montée en flèche de la criminalité en Tunisie constitue une source d’inquiétude.<br>De ce fait, notre site vient donner des renseignements aux utilisateurs sur les lieux des crimes afin de facilement localiser les places dite a risque et diminuer donc le taux des agressions perpétrées à l’encontre de nos citoyens dans les grandes villes.</p>
</div>

{% endblock %}
{% block content %}
{% block body_block_right %}
<div class="hero-unit">
<div id="main-slider" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#main-slider" data-slide-to="0" class="active"></li>
				<li data-target="#main-slider" data-slide-to="1"></li>
				<li data-target="#main-slider" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">
				<div class="item active">
					<img class="img-responsive" src="/static/images/slider/bg1.jpg" alt="slider">
					<div class="carousel-caption">
						<h2>register for our next event </h2>
						<h4>full event package only @$199</h4>
						<a href="#contact">GRAB YOUR TICKETS <i class="fa fa-angle-right"></i></a>
					</div>
				</div>
				<div class="item">
					<img class="img-responsive" src="/static/images/slider/bg2.jpg" alt="slider">
					<div class="carousel-caption">
						<h2>register for our next event </h2>
						<h4>full event package only @$199</h4>
						<a href="#contact">GRAB YOUR TICKETS <i class="fa fa-angle-right"></i></a>
					</div>
				</div>
				<div class="item">
					<img class="img-responsive" src="/static/images/slider/bg3.jpg" alt="slider">
					<div class="carousel-caption">
						<h2>register for our next event </h2>
						<h4>full event package only @$199</h4>
						<a href="#contact" >GRAB YOUR TICKETS <i class="fa fa-angle-right"></i></a>
					</div>
				</div>
			</div>
		</div>
</div>
{% endblock %}
{%  endblock %}
{% block scripts %}
{% endblock %}
</body>
</html>

templates/crime/add_crime.html
{% extends  'crime/base.html' %}
{%  load static %}
{% block title %}ajout d'un crime ! {% endblock %}
{% block content %}
<div class="col-sm-4">	
 <h4>De quel crime etes vous la victime ? </h4>

	
        <form id="crime_form" method="post" action="/crime/new_crime/" style="color:#000000">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
		</br>
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
		<div class="form-group">
                {{ field.help_text }}
		</br>
                {{ field }}
		</div>
	</br>
            {% endfor %}

            <button class="btn btn-primary" type="submit" name="submit" > envoyer </button> 
</form>
    
</div>
<div class="col-sm-8">
 <h2 style="color:#244994;">Marquer la place du crime</h2>

{% include 'crime/gmindex.html' %}
            <script src="{% static 'js/add_script.js' %}"></script>
</div>
{% endblock %}

templates/crime/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
        <title> {% block title %}donner le titre ! {% endblock %}</title>
    {% block style %}
    {% endblock %}
        <style>
               .carousel-inner {
                    overflow: visible;
    </style>
    </head>

    <body>
<header id="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
			<div class="container">
		            <div class="navbar-header">
		                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		                    <span class="sr-only">Toggle navigation</span>
		                    <span class="icon-bar"></span>
		                    <span class="icon-bar"></span>
		                    <span class="icon-bar"></span>
		                </button>
		                <a class="navbar-brand" href="/crime/acceuil/">
		                	<img class="img-responsive" src="/static/images/logo.png" alt="logo">
		                </a>
		            </div>
		            <div class="navbar-collapse collapse">
		                <ul class="nav navbar-nav navbar-right">
		                    <li class="active"><a href="/crime/acceuil/">Home</a></li>
		                    <li ><a href="/crime/new_crime/">ajouter un crime</a></li>
		                    <li ><a href="/crime/mod/">modifier un crime</a></li>
		                    <li ><a href="/crime/statistique/">crimes</a></li>
		                    <li ><a href="/crime/test/">calendrier</a></li>
		                    <li ><a href="#">Contact</a></li>
		                </ul>
		            </div>
		        </div>
    </header>
    <!--/#header-->
{% block content %}

{% endblock %}
<script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/smoothscroll.js' %}"></script>
<script src="{% static 'js/jquery.parallax.js' %}"></script>
<script src="{% static 'js/jquery.nav.js' %}"></script>
<!-- <script src="{% static 'js/main.js' %}"></script> -->
{% block script %}
{% endblock %}
</body>
</html>

templates/crime/calendar.html
<!DOCTYPE html>
<html>
{% extends 'crime/base.html' %}
{% load static %}
<head>
    <title>calender</title>
{% block style %}
    <link href="{% static 'css/cal-heatmap.css' %}" rel="stylesheet">
{% endblock %}    
<style>
        button {
            width:60px;
            height: 30px;
        }
    </style>
</head>
<body>
{% block content %}
<div id="calender"></div><button id="prev">prev</button><button id="next">next</button>
<hr>
<div id="calender1"></div><button id="prev1">prev</button><button id="next1">next</button>
<hr>
<div id="calender2"></div><button id="prev2">prev</button><button id="next2">next</button>
<script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
<script src="http://d3js.org/d3.v3.min.js"></script>
<script src="{% static 'js/cal-heatmap.min.js' %}"></script>
<script src="{% static 'js/calender.js' %}"></script>
{% endblock %}
</body>
</html>

templates/crime/gmindex.html
{% load static %}
    <input id="searchBox" type="text">
    <div id="map-canvas" style="height: 880px;width: 100%;float:left;border:solid 4px #002A46; "></div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAad2xRPPwwSZw4-wrLRdTiLZLXjjdzRI4&libraries=places"></script>
    <script src="{% static 'js/markerclusterer.js' %}"></script>
    <script src="{%  static 'js/jquery-2.1.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>

<div></div>

templates/crime/mod_crime.html
<!DOCTYPE html>
<html>
{% extends 'crime/base.html' %}
{% load static %}
<head>
    <title>{% block title %}modifier une crime{% endblock %}</title>
    {% block style %}
        <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
    {% endblock %}
</head>
<body>
{% block content %}
<div class="col-sm-8">
    {% include 'crime/gmindex.html' %}
</div>
<div class="col-sm-4">
    <form style="color: #000000" method="post" action="/crime/modifier/">
    {% csrf_token %}
    <input type="hidden" value="" id="id_id" name="id" class="form-group">
    {% for Hfield in form.hidden_fields %}
	{{ Hfield }}
    {% endfor %}
    {% for Vfield in form.visible_fields %}
	{{ Vfield.errors }}
	<div class="form-group">
	{{ Vfield.help_text }}
	{{ Vfield }}
	</div>
    {% endfor %}
    <input type="submit" class="btn btn-success" value="send">
    </form>
</div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/mod_crime.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.js' %}" ></script>
    <script>
        $(document).ready(function(){
            $('#id_time').datetimepicker({
                pick12HourFormat: false,
                format: 'YYYY-MM-DD HH:mm:ss'
            });
        })
    </script>
{% endblock %}
</body>
</html>

templates/crime/statistique.html
{% extends 'crime/base.html' %}
{% load static %}
{% block title %} statistique {% endblock %}
{% block style %}
{% endblock %}
{% block content %}
    <div class="hero-unit">
        <div class="col-sm-6 active" id="container_type"></div>
        <div class="col-sm-6 active" id="container_sex"></div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
    <script src="{% static 'js/highcharts.js' %}"></script>
    <script src="{% static 'js/stat1.js' %}" ></script>
    <script>
       $(document).ready(function(){
           plot_sex_stat(baseConfig);
           plot_type_stat(baseConfig);
});
    </script>
{% endblock %}

templates/crime/thanks.html
{% extends 'crime/base.html' %}
{% load static %}
{% block title %}thanks{% endblock %}

{% block body_block_left %}
</br>
</br>
</br>
<div class="hero-unit">
<h1> Merci pour votre aide</h1>
</div>
{% endblock %}
{% block body_block_right %}
</br> 
</br>
</br>
<img src="{% static 'tunisia.jpg' %}" >
 {% endblock %}